### ISSUE TITLE
SAIL_ERROR_CODEC_NOT_FOUND when installing via vckpkg on windows

### ISSUE THREAD

**Issue by M0liusX** [happy-fox-shark/sail#52]
config.h shows that the codecs should be stored in path "...\\vcpkg\\packages\\sail_x64-windows-static\\lib\\sail\\codecs"
However no such folder or file named sail\\codecs exists in path "...\\vcpkg\\packages\\sail_x64-windows-static\\lib\\"

I am just trying to read a jpg or png file, but I keep getting the codec not found error. I have only tried x64-windows-static and x64-windows versions however.

**Comment by smoked-herring** [comment]
Hi! Thanks for the report!

Sail also prints debug messages in stderr. Could you please attach its full output? I hope it helps to identify the issue.

**Comment by M0liusX** [comment]
----------------------------------------------------------------------------------------------------------------------------------
SAIL: [D] [codec_info.c:46] Finding codec info for path 'images/cat.jpg'
SAIL: [D] [codec_info.c:150] Finding codec info for extension 'jpg'
SAIL: [D] [context_private.c:681] Allocated a new thread-local context 0000012BE6E76770
SAIL: [I] [context_private.c:640] Version 0.9.0
SAIL: [D] [context_private.c:54] Add 'C:\Users\mam19\Documents\GIT\OpenGL\x64\Debug' to the DLL search paths
SAIL: [E] [context_private.c:532] Failed to resolve 'sail_codec_info_gif'. Error: 127
SAIL: [E] [context_private.c:532] Failed to resolve 'sail_codec_info_jpeg'. Error: 127
SAIL: [E] [context_private.c:532] Failed to resolve 'sail_codec_info_png'. Error: 127
SAIL: [E] [context_private.c:532] Failed to resolve 'sail_codec_info_tiff'. Error: 127
SAIL: [D] [context_private.c:183] SAIL_MY_CODECS_PATH environment variable is set. Loading codecs from 'C:\\Users\\mam19\\Documents\\GIT\\vcpkg\\packages\\sail_x64-windows-static\\lib\\sail\\codecs'
SAIL: [D] [context_private.c:197] Optional DLL directory 'C:\\Users\\mam19\\Documents\\GIT\\vcpkg\\packages\\sail_x64-windows-static\\lib\\sail\\codecs\lib' doesn't exist, so not loading DLLs from it
SAIL: [D] [context_private.c:388] Enumerating codecs in 'C:\\Users\\mam19\\Documents\\GIT\\vcpkg\\packages\\sail_x64-windows-static\\lib\\sail\\codecs'
SAIL: [E] [context_private.c:406] Failed to list files in 'C:\\Users\\mam19\\Documents\\GIT\\vcpkg\\packages\\sail_x64-windows-static\\lib\\sail\\codecs'. Error: 3. No codecs loaded from it
SAIL: [E] [context_private.c:623] 

*** No codecs were found. Please check the installation directory. ***

SAIL: [D] [context_private.c:357] Enumerated codecs:
SAIL: [D] [context_private.c:662] Initialized in 4 ms.
SAIL: [E] [codec_info.c:181] SAIL_ERROR_CODEC_NOT_FOUND

----------------------------------------------------------------------------------------------------------------------------------

Seems like the files just do not exist. Was the build supposed generate a directory with the codecs?

**Comment by smoked-herring** [comment]
What's your Windows version? It would be also great to have a small demo application from you to reproduce the issue. I'll try to reproduce it on the next week.

Technical details: With vcpkg, all codecs are combined in a single dll sail-codecs.dll. Then it's opened in runtime and I search for symbols identifiying codecs (sail_codec_info_xxx). It's interesting that they're not found in the dll. I'll look into it.

**Comment by M0liusX** [comment]
There are no dlls in the sail_x64-windows-static build version since there is no bin folder. Maybe that is the problem?

By the way another issue I had was that the include path for for vckpkg looks like this for sail:
sail/sail/sail/
sail/sail/sail-c++
sail/sail/sail-common

but all the header files are set as the following:
sail/sail/
sail/sail-c++
sail/sail-common

I was able to easily fix it by adding ".../vckpkg/.../includes/sail/" to my includes, but would be nice if it was set up to work outside the box without having to add extra lines to my includes. Don't know if this is relavent to the problem. I do not think it is, but the more information you have the better. I will go ahead and try to make a simple project for vscode, but I will probably take a while since it is already getting late where I am from.

**Comment by smoked-herring** [comment]
For static builds we have a static version of it: sail-codecs.lib.

BTW, do you use cmake to configure your project, or it's a native msvs project? Sail provides cmake configs. So with cmake you automatically get correct include paths.

**Comment by smoked-herring** [comment]
Have you had a chance to prepare a small demo? Or, hopefully, you fixed the issue locally?
